openapi: 3.0.1
info:
  title: bookshop
  version: v0
servers:
  - url: http://localhost:8080/books
paths:
  /updateBook/{id}:
    put:
      tags:
        - book-controller
      operationId: updateBook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCreateRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BookResponse'
  /addBook:
    post:
      tags:
        - book-controller
      operationId: createBook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCreateRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BookResponse'
  /getBook:
    get:
      tags:
        - book-controller
      operationId: getBook
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookResponse'
  /getBookByGenre/{gen}:
    get:
      tags:
        - book-controller
      operationId: getBookByGenre
      parameters:
        - name: gen
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookResponse'
  /getBook/{id}:
    get:
      tags:
        - book-controller
      operationId: getBookById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BookResponse'
  /deleteBook/{id}:
    delete:
      tags:
        - book-controller
      operationId: deleteBook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
  /order-report:
    get:
      tags:
        - book-controller
      operationId: orderBooks
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookOrder'
components:
  schemas:
    BookDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        genre:
          type: string
        price:
          type: number
          format: double
        pages:
          type: integer
        visitCount:
          type: integer
        availableCopies:
          type: integer
        author:
          $ref: '#/components/schemas/Author'
    BookCreateRequest:
      type: object
      properties:
        title:
          type: string
        genre:
          type: string
        price:
          type: number
          format: double
        pages:
          type: integer
        availableCopies:
          type: integer
        author:
          type: string
          format: uuid
    BookResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        author:
          type: string
          format: uuid
        genre:
          type: string
        price:
          type: number
          format: double
        Pages:
          type: integer
        availableCopies:
          type: integer
    Author:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    BookOrder:
      type: object
      properties:
        bookId:
          type: string
          format: uuid
        quantity:
          type: integer